import ClientLayout from "@/components/ClientLayout";
import CurvedDivider from "@/components/CurvedDivider";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import ReadyToMove from "@/components/ReadyToMove";
import type { Metadata } from "next";
import { Instrument_Sans } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

const instrument = Instrument_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${instrument.className} antialiased`}>
        <ClientLayout>
          <Navbar />
          {children}
          <CurvedDivider />

          {/* CONTAINER */}
          <div className="mx-auto w-full max-w-[1400px]">
            <ReadyToMove />
          </div>
          <Footer />
        </ClientLayout>
        <Toaster position="top-center" richColors />
      </body>
    </html>
  );
}
